name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
        - jruby-1.7.9
        - 2.4.10
        - 2.5.8
        - 2.6.6
        - 2.7.1
        - 2.7.2
        gemfile:
        - gemfiles/rails5_0.gemfile
        - gemfiles/rails5_1.gemfile
        - gemfiles/rails5_2.gemfile
        - gemfiles/rails6_0.gemfile
        exclude:
          - ruby-version: 2.4.10
            gemfile: gemfiles/rails6_0.gemfile
    env:
      JRUBY_OPTS: "--1.9"
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby-version }}"
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.4
    - name: Install dependencies
      run: "bundle install --without development"
    - name: Run tests
      run: "bundle exec rake"
